import { KnowledgeImportStatus, KnowledgeReviewStatus, KnowledgeSourceStatus, type Prisma } from "@prisma/client";
import { getPrismaClient } from "@/lib/db/prisma";
import { validateKnowledgeEntityEnvelope, type KnowledgeEntityInput } from "@/schemas/knowledge-entity-envelope";
const commercial = new Set(["CC0-1.0", "CC-BY-4.0", "INTERNAL-APPROVED"]);
type Item = { entity: KnowledgeEntityInput; sourceId: string; citation: string; reviewerStatus: KnowledgeReviewStatus; scientificReview: KnowledgeReviewStatus; imageRights?: { imageSource: string; owner: string; license: string; attributionText?: string; permittedUse: string; originalUrl: string; checksum: string; approvalStatus: KnowledgeReviewStatus }; treatments?: Array<{ authorityReviewed: boolean; contraindications?: string; sourceId?: string }> };
export async function validateBatch(batchId: string) { const prisma = getPrismaClient(); const items = await prisma.knowledgeImportItem.findMany({ where: { batchId } }); const errors: string[] = []; for (const item of items) { const record = item.payload as unknown as Item; try { validateKnowledgeEntityEnvelope(record.entity); const source = await prisma.knowledgeSource.findUnique({ where: { id: record.sourceId } }); if (!source || source.status !== KnowledgeSourceStatus.APPROVED || !source.commercialUseAllowed || !commercial.has(source.license)) throw new Error("approved commercial source required"); if (!record.citation || record.reviewerStatus !== KnowledgeReviewStatus.APPROVED || record.scientificReview !== KnowledgeReviewStatus.APPROVED) throw new Error("reviewed citation required"); if (record.imageRights && (record.imageRights.approvalStatus !== KnowledgeReviewStatus.APPROVED || !commercial.has(record.imageRights.license))) throw new Error("approved image rights required"); for (const treatment of record.treatments ?? []) if (!treatment.authorityReviewed || (treatment.contraindications && !treatment.sourceId)) throw new Error("treatment authority required"); } catch (error) { errors.push(`${item.entityId}:${error instanceof Error ? error.message : "invalid"}`); } } await prisma.knowledgeImportBatch.update({ where: { id: batchId }, data: { status: errors.length ? KnowledgeImportStatus.FAILED : KnowledgeImportStatus.VALIDATED, report: { errors, count: items.length } as Prisma.InputJsonValue } }); return { valid: !errors.length, errors, count: items.length }; }
export async function approveBatch(batchId: string, reviewer: string) { const batch = await getPrismaClient().knowledgeImportBatch.findUniqueOrThrow({ where: { id: batchId } }); if (batch.status !== KnowledgeImportStatus.VALIDATED) throw new Error("BATCH_NOT_VALIDATED"); await getPrismaClient().knowledgeImportBatch.update({ where: { id: batchId }, data: { status: KnowledgeImportStatus.APPROVED, approvedBy: reviewer, approvedAt: new Date() } }); }
export async function importBatch(batchId: string) { const prisma = getPrismaClient(); const batch = await prisma.knowledgeImportBatch.findUniqueOrThrow({ where: { id: batchId }, include: { items: true } }); if (batch.status !== KnowledgeImportStatus.APPROVED) throw new Error("BATCH_NOT_APPROVED"); await prisma.$transaction(async (tx) => { for (const item of batch.items) { const record = item.payload as unknown as Item; await tx.knowledgeEntity.upsert({ where: { id: record.entity.id }, create: { ...record.entity, payload: record.entity.payload as Prisma.InputJsonValue }, update: { ...record.entity, payload: record.entity.payload as Prisma.InputJsonValue } }); await tx.knowledgeProvenance.upsert({ where: { entityId_sourceId_version: { entityId: record.entity.id, sourceId: record.sourceId, version: batch.version } }, create: { entityId: record.entity.id, sourceId: record.sourceId, citation: record.citation, reviewerStatus: record.reviewerStatus, scientificReview: record.scientificReview, version: batch.version, importBatchId: batchId }, update: {} }); if (record.imageRights) await tx.knowledgeImageRights.upsert({ where: { checksum: record.imageRights.checksum }, create: { entityId: record.entity.id, ...record.imageRights }, update: {} }); } await tx.knowledgeImportBatch.update({ where: { id: batchId }, data: { status: KnowledgeImportStatus.IMPORTED, importedAt: new Date() } }); }); }
export async function rollbackBatch(batchId: string) { const prisma = getPrismaClient(); const batch = await prisma.knowledgeImportBatch.findUniqueOrThrow({ where: { id: batchId }, include: { items: true } }); await prisma.$transaction(async (tx) => { await tx.knowledgeProvenance.deleteMany({ where: { importBatchId: batchId } }); await tx.knowledgeImageRights.deleteMany({ where: { entityId: { in: batch.items.map((item) => item.entityId) } } }); await tx.knowledgeEntity.deleteMany({ where: { id: { in: batch.items.map((item) => item.entityId) } } }); await tx.knowledgeImportBatch.update({ where: { id: batchId }, data: { status: KnowledgeImportStatus.ROLLED_BACK, rolledBackAt: new Date() } }); }); }
