import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import type { Prisma } from "@prisma/client";
import { authOptions } from "@/lib/auth/options";
import { UserRole } from "@/lib/auth/roles";
import { getPrismaClient } from "@/lib/db/prisma";
import { canCreateDisease, canViewDiseases } from "@/lib/diseases/disease-permissions";
import { DiseaseService } from "@/lib/diseases/disease-service";
async function actor() { const session = await getServerSession(authOptions); if (!session?.user?.id || !session.user.role) throw new Error("UNAUTHORIZED"); return { id: session.user.id, role: session.user.role as UserRole }; }
const first = (value: string | null, allowed: readonly string[]) => value && allowed.includes(value) ? value : undefined;
export async function GET(request: Request) { try { const current = await actor(); if (!canViewDiseases(current.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const p = new URL(request.url).searchParams, page = Math.max(1, Number.parseInt(p.get("page") ?? "1", 10) || 1), pageSize = Math.min(50, Math.max(1, Number.parseInt(p.get("pageSize") ?? "20", 10) || 20)), q = (p.get("q") ?? "").trim(), classification = first(p.get("classification"), ["FUNGAL", "BACTERIAL", "VIRAL", "OOMYCETE", "PHYSIOLOGICAL_DISORDER"]), severity = first(p.get("severity"), ["LOW", "MODERATE", "HIGH", "CRITICAL"]), publicationState = first(p.get("publicationState"), ["DRAFT", "PUBLISHED", "ARCHIVED"]), syncStatus = first(p.get("syncStatus"), ["PENDING", "SYNCED", "FAILED"]), sort = first(p.get("sort"), ["updatedAt", "createdAt", "name"]) ?? "updatedAt", direction: Prisma.SortOrder = p.get("direction") === "asc" ? "asc" : "desc"; const where: Prisma.DiseaseWhereInput = { ...(classification ? { classification: classification as Prisma.EnumDiseaseClassificationFilter["equals"] } : {}), ...(severity ? { severity: severity as Prisma.EnumDiseaseSeverityFilter["equals"] } : {}), ...(publicationState ? { entity: { publicationState: publicationState as Prisma.EnumKnowledgePublicationStateFilter["equals"] } } : {}), ...(syncStatus ? { syncState: { is: { status: syncStatus as Prisma.EnumKnowledgeSyncStatusFilter["equals"] } } } : {}), ...(q ? { OR: [{ entity: { name: { contains: q, mode: "insensitive" } } }, { scientificName: { contains: q, mode: "insensitive" } }, { aliases: { some: { normalizedValue: { contains: q.toLowerCase() } } } }, { symptoms: { some: { normalizedValue: { contains: q.toLowerCase() } } } }] } : {}) }; const db = getPrismaClient(), include = { entity: true, aliases: true, symptoms: true, images: { orderBy: { sortOrder: "asc" as const } }, syncState: true, plants: true }, orderBy: Prisma.DiseaseOrderByWithRelationInput = sort === "name" ? { entity: { name: direction } } : { [sort]: direction }; const [items, total] = await Promise.all([db.disease.findMany({ where, include, skip: (page - 1) * pageSize, take: pageSize, orderBy }), db.disease.count({ where })]); return NextResponse.json({ items, total, page, pageSize, pageCount: Math.max(1, Math.ceil(total / pageSize)) }); } catch { return NextResponse.json({ error: "Access denied" }, { status: 401 }); } }
export async function POST(request: Request) { try { const current = await actor(); if (!canCreateDisease(current.role)) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); return NextResponse.json(await new DiseaseService().create(await request.json(), current), { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Disease could not be created" }, { status: 400 }); } }
