import { randomUUID } from "node:crypto";
import type { PrismaClient } from "@prisma/client";
import { getPrismaClient } from "@/lib/db/prisma";
import { UserRole } from "@/lib/auth/roles";
import { toPlantSlug } from "@/lib/plants/plant-slug";
import { createKnowledgeExportStore } from "@/lib/knowledge/export/knowledge-export-store-factory";
import { KnowledgeGenerator } from "@/lib/knowledge/knowledge-generator";
import { createPrismaKnowledgeEntityRepository } from "@/lib/knowledge/prisma/prisma-knowledge-repository";
import { PrismaKnowledgeReleaseRepository } from "@/lib/knowledge/prisma/prisma-knowledge-release-repository";
import { normalizePestValue, validatePestInput, type PestInput } from "@/schemas/pest";
export class PestService {
  constructor(private readonly prisma: PrismaClient = getPrismaClient(), private readonly generate = () => new KnowledgeGenerator(createPrismaKnowledgeEntityRepository(this.prisma), new PrismaKnowledgeReleaseRepository(this.prisma), createKnowledgeExportStore()).generate()) {}
  async create(input: PestInput, actor: { id: string; role: UserRole }) { validatePestInput(input); const id = randomUUID(), slug = toPlantSlug(input.slug || input.name); if (!slug) throw new Error("Pest slug is invalid."); const publicationState = actor.role === UserRole.AGRONOMIST ? "DRAFT" : input.publicationState ?? "DRAFT"; const pest = await this.prisma.$transaction(async (tx) => { await tx.knowledgeEntity.create({ data: { id, type: "PEST", slug, name: input.name.trim(), payload: {}, schemaVersion: 1, publicationState } }); return tx.pest.create({ data: { id, classification: input.classification, severity: input.severity, economicImpact: input.economicImpact, scientificName: input.scientificName?.trim() || null, description: input.description?.trim() || null, createdByUserId: actor.id, aliases: { create: (input.aliases ?? []).map((value) => ({ value: value.trim(), normalizedValue: normalizePestValue(value) })) }, symptoms: { create: (input.symptoms ?? []).map((value) => ({ value: value.trim(), normalizedValue: normalizePestValue(value) })) }, damagePatterns: { create: (input.damagePatterns ?? []).map((value) => ({ value: value.trim(), normalizedValue: normalizePestValue(value) })) }, lifecycleStages: { create: (input.lifecycleStages ?? []).map((value, sortOrder) => ({ value: value.trim(), normalizedValue: normalizePestValue(value), sortOrder })) }, plants: { create: input.plants ?? [] }, syncState: { create: { status: "PENDING" } } }, include: { entity: true, syncState: true } }); }); await this.sync(id); return pest; }
  async sync(pestId: string) { await this.prisma.pestKnowledgeSync.update({ where: { pestId }, data: { status: "PENDING", diagnosticCode: null } }); try { await this.generate(); await this.prisma.pestKnowledgeSync.update({ where: { pestId }, data: { status: "SYNCED", lastSyncedAt: new Date(), diagnosticCode: null } }); } catch { await this.prisma.pestKnowledgeSync.update({ where: { pestId }, data: { status: "FAILED", diagnosticCode: "KNOWLEDGE_EXPORT_FAILED" } }); throw new Error("Knowledge export failed."); } }
}
