CREATE TYPE "PlantCategory" AS ENUM ('CROP', 'HOME_PLANT', 'ORNAMENTAL');
CREATE TYPE "KnowledgeSyncStatus" AS ENUM ('PENDING', 'SYNCED', 'FAILED');
CREATE TYPE "StorageCleanupStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED');
CREATE TABLE "Plant" ("id" TEXT NOT NULL, "category" "PlantCategory" NOT NULL, "scientificName" TEXT, "description" TEXT, "createdByUserId" TEXT NOT NULL, "updatedByUserId" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Plant_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PlantAlias" ("id" TEXT NOT NULL, "plantId" TEXT NOT NULL, "value" TEXT NOT NULL, "normalizedValue" TEXT NOT NULL, "locale" TEXT, CONSTRAINT "PlantAlias_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PlantImage" ("id" TEXT NOT NULL, "plantId" TEXT NOT NULL, "storageKey" TEXT NOT NULL, "url" TEXT NOT NULL, "alt" TEXT NOT NULL, "contentType" TEXT NOT NULL, "fileSize" INTEGER NOT NULL CHECK ("fileSize" >= 0), "width" INTEGER NOT NULL CHECK ("width" >= 0), "height" INTEGER NOT NULL CHECK ("height" >= 0), "checksum" TEXT NOT NULL, "sortOrder" INTEGER NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PlantImage_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PlantKnowledgeSync" ("plantId" TEXT NOT NULL, "status" "KnowledgeSyncStatus" NOT NULL DEFAULT 'PENDING', "lastSyncedAt" TIMESTAMP(3), "diagnosticCode" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PlantKnowledgeSync_pkey" PRIMARY KEY ("plantId"));
CREATE TABLE "StorageCleanupJob" ("id" TEXT NOT NULL, "storageKey" TEXT NOT NULL, "status" "StorageCleanupStatus" NOT NULL DEFAULT 'PENDING', "retryCount" INTEGER NOT NULL DEFAULT 0, "diagnosticCode" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StorageCleanupJob_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PlantAlias_plantId_normalizedValue_key" ON "PlantAlias"("plantId", "normalizedValue");
CREATE INDEX "PlantAlias_normalizedValue_idx" ON "PlantAlias"("normalizedValue");
CREATE UNIQUE INDEX "PlantImage_storageKey_key" ON "PlantImage"("storageKey");
CREATE UNIQUE INDEX "PlantImage_plantId_sortOrder_key" ON "PlantImage"("plantId", "sortOrder");
CREATE INDEX "Plant_category_idx" ON "Plant"("category"); CREATE INDEX "Plant_createdByUserId_idx" ON "Plant"("createdByUserId"); CREATE INDEX "PlantKnowledgeSync_status_idx" ON "PlantKnowledgeSync"("status"); CREATE INDEX "StorageCleanupJob_status_idx" ON "StorageCleanupJob"("status");
CREATE UNIQUE INDEX "StorageCleanupJob_storageKey_key" ON "StorageCleanupJob"("storageKey");
ALTER TABLE "Plant" ADD CONSTRAINT "Plant_id_fkey" FOREIGN KEY ("id") REFERENCES "KnowledgeEntity"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Plant" ADD CONSTRAINT "Plant_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Plant" ADD CONSTRAINT "Plant_updatedByUserId_fkey" FOREIGN KEY ("updatedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PlantAlias" ADD CONSTRAINT "PlantAlias_plantId_fkey" FOREIGN KEY ("plantId") REFERENCES "Plant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlantImage" ADD CONSTRAINT "PlantImage_plantId_fkey" FOREIGN KEY ("plantId") REFERENCES "Plant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PlantKnowledgeSync" ADD CONSTRAINT "PlantKnowledgeSync_plantId_fkey" FOREIGN KEY ("plantId") REFERENCES "Plant"("id") ON DELETE CASCADE ON UPDATE CASCADE;
